/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddMarkInput {
  'studentId' : StudentId,
  'maxScore' : bigint,
  'subject' : string,
  'date' : Timestamp,
  'assessmentName' : string,
  'score' : bigint,
}
export interface AddUserInput {
  'username' : string,
  'password' : string,
  'name' : string,
  'roleId' : string,
}
export type AddUserResult = { 'ok' : UserProfile } |
  { 'err' : string };
export type AttendanceId = bigint;
export interface AttendanceRateSummary {
  'presentCount' : bigint,
  'attendanceRate' : bigint,
  'lateCount' : bigint,
  'totalRecords' : bigint,
  'absentCount' : bigint,
}
export interface AttendanceRecord {
  'id' : AttendanceId,
  'status' : AttendanceStatus,
  'studentId' : StudentId,
  'date' : Timestamp,
  'markedBy' : string,
}
export type AttendanceStatus = { 'Present' : null } |
  { 'Late' : null } |
  { 'Absent' : null };
export interface AttendanceSummary {
  'studentId' : StudentId,
  'presentDays' : bigint,
  'totalDays' : bigint,
  'lateDays' : bigint,
  'absentDays' : bigint,
}
export type Audience = { 'All' : null } |
  { 'Teacher' : null } |
  { 'Student' : null } |
  { 'Admin' : null } |
  { 'Class' : null };
export interface CreateFeeInput {
  'studentId' : StudentId,
  'lateFeeAmount' : bigint,
  'dueDate' : Timestamp,
  'amount' : bigint,
  'receiptNumber' : string,
}
export interface CreateHomeworkInput {
  'title' : string,
  'createdBy' : string,
  'dueDate' : Timestamp,
  'description' : string,
  'classId' : string,
}
export interface CreateNoticeInput {
  'title' : string,
  'content' : string,
  'createdBy' : string,
  'audience' : Audience,
  'classId' : [] | [string],
}
export interface CreateStudentInput {
  'parentContact' : string,
  'grNo' : string,
  'class' : string,
  'name' : string,
  'section' : string,
  'photoUrl' : string,
}
export interface CreateTeacherInput {
  'classesAssigned' : Array<string>,
  'subjects' : Array<string>,
  'name' : string,
  'teacherId' : string,
}
export interface EnrollmentByClass {
  'classId' : string,
  'studentCount' : bigint,
}
export type FeeId = bigint;
export interface FeeRecord {
  'id' : FeeId,
  'status' : FeeStatus,
  'studentId' : StudentId,
  'lateFeeAmount' : bigint,
  'dueDate' : Timestamp,
  'paidDate' : [] | [Timestamp],
  'amount' : bigint,
  'receiptNumber' : string,
}
export type FeeStatus = { 'Late' : null } |
  { 'Paid' : null } |
  { 'Unpaid' : null };
export interface FeesCollectionSummary {
  'lateAmount' : bigint,
  'totalAmount' : bigint,
  'pendingAmount' : bigint,
  'collectedAmount' : bigint,
}
export interface Homework {
  'id' : HomeworkId,
  'title' : string,
  'createdAt' : Timestamp,
  'createdBy' : string,
  'dueDate' : Timestamp,
  'description' : string,
  'classId' : string,
}
export type HomeworkId = bigint;
export interface HomeworkSubmission {
  'status' : SubmissionStatus,
  'studentId' : StudentId,
  'homeworkId' : HomeworkId,
  'submittedAt' : Timestamp,
}
export type LoginResult = { 'ok' : string } |
  { 'err' : string };
export interface Mark {
  'id' : MarkId,
  'studentId' : StudentId,
  'maxScore' : bigint,
  'subject' : string,
  'date' : Timestamp,
  'assessmentName' : string,
  'score' : bigint,
}
export interface MarkAttendanceInput {
  'status' : AttendanceStatus,
  'studentId' : StudentId,
  'date' : Timestamp,
  'markedBy' : string,
}
export type MarkId = bigint;
export interface Notice {
  'id' : NoticeId,
  'title' : string,
  'content' : string,
  'createdAt' : Timestamp,
  'createdBy' : string,
  'audience' : Audience,
  'classId' : [] | [string],
}
export type NoticeId = bigint;
export type Role = { 'Teacher' : null } |
  { 'Student' : null } |
  { 'Admin' : null };
export interface Student {
  'id' : StudentId,
  'parentContact' : string,
  'grNo' : string,
  'class' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'section' : string,
  'photoUrl' : string,
}
export type StudentId = bigint;
export type SubmissionStatus = { 'Submitted' : null } |
  { 'Pending' : null };
export interface Teacher {
  'id' : TeacherId,
  'classesAssigned' : Array<string>,
  'subjects' : Array<string>,
  'name' : string,
  'createdAt' : Timestamp,
  'teacherId' : string,
}
export type TeacherId = bigint;
export type Timestamp = bigint;
export interface UpdateFeeInput {
  'id' : FeeId,
  'status' : FeeStatus,
  'lateFeeAmount' : bigint,
  'dueDate' : Timestamp,
  'amount' : bigint,
  'receiptNumber' : string,
}
export interface UpdateMarkInput {
  'id' : MarkId,
  'maxScore' : bigint,
  'assessmentName' : string,
  'score' : bigint,
}
export interface UpdateStudentInput {
  'id' : StudentId,
  'parentContact' : string,
  'grNo' : string,
  'class' : string,
  'name' : string,
  'section' : string,
  'photoUrl' : string,
}
export interface UpdateTeacherInput {
  'id' : TeacherId,
  'classesAssigned' : Array<string>,
  'subjects' : Array<string>,
  'name' : string,
  'teacherId' : string,
}
export interface UserProfile {
  'id' : string,
  'username' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : Role,
  'roleId' : string,
}
export interface _SERVICE {
  'addMark' : ActorMethod<[string, AddMarkInput], Mark>,
  'addUser' : ActorMethod<[string, AddUserInput], AddUserResult>,
  'createFeeRecord' : ActorMethod<[string, CreateFeeInput], FeeRecord>,
  'createHomework' : ActorMethod<[string, CreateHomeworkInput], Homework>,
  'createNotice' : ActorMethod<[string, CreateNoticeInput], Notice>,
  'createStudent' : ActorMethod<[string, CreateStudentInput], Student>,
  'createTeacher' : ActorMethod<[string, CreateTeacherInput], Teacher>,
  'deleteNotice' : ActorMethod<[string, NoticeId], boolean>,
  'deleteStudent' : ActorMethod<[string, StudentId], boolean>,
  'deleteTeacher' : ActorMethod<[string, TeacherId], boolean>,
  'getAttendanceByClass' : ActorMethod<
    [string, string, Timestamp],
    Array<AttendanceRecord>
  >,
  'getAttendanceByStudent' : ActorMethod<
    [string, StudentId],
    Array<AttendanceRecord>
  >,
  'getAttendanceRateSummary' : ActorMethod<[], AttendanceRateSummary>,
  'getAttendanceSummary' : ActorMethod<[string, StudentId], AttendanceSummary>,
  'getEnrollmentByClass' : ActorMethod<[], Array<EnrollmentByClass>>,
  'getFeesCollectionSummary' : ActorMethod<[], FeesCollectionSummary>,
  'getMarksByStudent' : ActorMethod<[string, StudentId], Array<Mark>>,
  'getMarksBySubject' : ActorMethod<[string, string], Array<Mark>>,
  'getStudent' : ActorMethod<[StudentId], [] | [Student]>,
  'getSubmissions' : ActorMethod<[HomeworkId], Array<HomeworkSubmission>>,
  'getTeacher' : ActorMethod<[TeacherId], [] | [Teacher]>,
  'getTotalStudents' : ActorMethod<[], bigint>,
  'getTotalTeachers' : ActorMethod<[], bigint>,
  'listAllFees' : ActorMethod<[], Array<FeeRecord>>,
  'listFeesByStudent' : ActorMethod<[StudentId], Array<FeeRecord>>,
  'listHomeworkByClass' : ActorMethod<[string], Array<Homework>>,
  'listNotices' : ActorMethod<[[] | [Audience], [] | [string]], Array<Notice>>,
  'listStudents' : ActorMethod<[], Array<Student>>,
  'listTeachers' : ActorMethod<[], Array<Teacher>>,
  'login' : ActorMethod<[string, string], LoginResult>,
  'logout' : ActorMethod<[string], undefined>,
  'markAttendance' : ActorMethod<
    [string, MarkAttendanceInput],
    AttendanceRecord
  >,
  'markFeePaid' : ActorMethod<[string, FeeId, Timestamp], [] | [FeeRecord]>,
  'markSubmission' : ActorMethod<
    [string, HomeworkId, StudentId],
    HomeworkSubmission
  >,
  'updateFeeRecord' : ActorMethod<[string, UpdateFeeInput], [] | [FeeRecord]>,
  'updateMark' : ActorMethod<[string, UpdateMarkInput], [] | [Mark]>,
  'updateStudent' : ActorMethod<[string, UpdateStudentInput], [] | [Student]>,
  'updateTeacher' : ActorMethod<[string, UpdateTeacherInput], [] | [Teacher]>,
  'validateSession' : ActorMethod<[string], [] | [UserProfile]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];