/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StudentId = IDL.Nat;
export const Timestamp = IDL.Int;
export const AddMarkInput = IDL.Record({
  'studentId' : StudentId,
  'maxScore' : IDL.Nat,
  'subject' : IDL.Text,
  'date' : Timestamp,
  'assessmentName' : IDL.Text,
  'score' : IDL.Nat,
});
export const MarkId = IDL.Nat;
export const Mark = IDL.Record({
  'id' : MarkId,
  'studentId' : StudentId,
  'maxScore' : IDL.Nat,
  'subject' : IDL.Text,
  'date' : Timestamp,
  'assessmentName' : IDL.Text,
  'score' : IDL.Nat,
});
export const AddUserInput = IDL.Record({
  'username' : IDL.Text,
  'password' : IDL.Text,
  'name' : IDL.Text,
  'roleId' : IDL.Text,
});
export const Role = IDL.Variant({
  'Teacher' : IDL.Null,
  'Student' : IDL.Null,
  'Admin' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Text,
  'username' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : Role,
  'roleId' : IDL.Text,
});
export const AddUserResult = IDL.Variant({
  'ok' : UserProfile,
  'err' : IDL.Text,
});
export const CreateFeeInput = IDL.Record({
  'studentId' : StudentId,
  'lateFeeAmount' : IDL.Nat,
  'dueDate' : Timestamp,
  'amount' : IDL.Nat,
  'receiptNumber' : IDL.Text,
});
export const FeeId = IDL.Nat;
export const FeeStatus = IDL.Variant({
  'Late' : IDL.Null,
  'Paid' : IDL.Null,
  'Unpaid' : IDL.Null,
});
export const FeeRecord = IDL.Record({
  'id' : FeeId,
  'status' : FeeStatus,
  'studentId' : StudentId,
  'lateFeeAmount' : IDL.Nat,
  'dueDate' : Timestamp,
  'paidDate' : IDL.Opt(Timestamp),
  'amount' : IDL.Nat,
  'receiptNumber' : IDL.Text,
});
export const CreateHomeworkInput = IDL.Record({
  'title' : IDL.Text,
  'createdBy' : IDL.Text,
  'dueDate' : Timestamp,
  'description' : IDL.Text,
  'classId' : IDL.Text,
});
export const HomeworkId = IDL.Nat;
export const Homework = IDL.Record({
  'id' : HomeworkId,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : IDL.Text,
  'dueDate' : Timestamp,
  'description' : IDL.Text,
  'classId' : IDL.Text,
});
export const Audience = IDL.Variant({
  'All' : IDL.Null,
  'Teacher' : IDL.Null,
  'Student' : IDL.Null,
  'Admin' : IDL.Null,
  'Class' : IDL.Null,
});
export const CreateNoticeInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdBy' : IDL.Text,
  'audience' : Audience,
  'classId' : IDL.Opt(IDL.Text),
});
export const NoticeId = IDL.Nat;
export const Notice = IDL.Record({
  'id' : NoticeId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : IDL.Text,
  'audience' : Audience,
  'classId' : IDL.Opt(IDL.Text),
});
export const CreateStudentInput = IDL.Record({
  'parentContact' : IDL.Text,
  'grNo' : IDL.Text,
  'class' : IDL.Text,
  'name' : IDL.Text,
  'section' : IDL.Text,
  'photoUrl' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : StudentId,
  'parentContact' : IDL.Text,
  'grNo' : IDL.Text,
  'class' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'section' : IDL.Text,
  'photoUrl' : IDL.Text,
});
export const CreateTeacherInput = IDL.Record({
  'classesAssigned' : IDL.Vec(IDL.Text),
  'subjects' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'teacherId' : IDL.Text,
});
export const TeacherId = IDL.Nat;
export const Teacher = IDL.Record({
  'id' : TeacherId,
  'classesAssigned' : IDL.Vec(IDL.Text),
  'subjects' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'teacherId' : IDL.Text,
});
export const AttendanceId = IDL.Nat;
export const AttendanceStatus = IDL.Variant({
  'Present' : IDL.Null,
  'Late' : IDL.Null,
  'Absent' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'id' : AttendanceId,
  'status' : AttendanceStatus,
  'studentId' : StudentId,
  'date' : Timestamp,
  'markedBy' : IDL.Text,
});
export const AttendanceRateSummary = IDL.Record({
  'presentCount' : IDL.Nat,
  'attendanceRate' : IDL.Nat,
  'lateCount' : IDL.Nat,
  'totalRecords' : IDL.Nat,
  'absentCount' : IDL.Nat,
});
export const AttendanceSummary = IDL.Record({
  'studentId' : StudentId,
  'presentDays' : IDL.Nat,
  'totalDays' : IDL.Nat,
  'lateDays' : IDL.Nat,
  'absentDays' : IDL.Nat,
});
export const EnrollmentByClass = IDL.Record({
  'classId' : IDL.Text,
  'studentCount' : IDL.Nat,
});
export const FeesCollectionSummary = IDL.Record({
  'lateAmount' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'pendingAmount' : IDL.Nat,
  'collectedAmount' : IDL.Nat,
});
export const SubmissionStatus = IDL.Variant({
  'Submitted' : IDL.Null,
  'Pending' : IDL.Null,
});
export const HomeworkSubmission = IDL.Record({
  'status' : SubmissionStatus,
  'studentId' : StudentId,
  'homeworkId' : HomeworkId,
  'submittedAt' : Timestamp,
});
export const LoginResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const MarkAttendanceInput = IDL.Record({
  'status' : AttendanceStatus,
  'studentId' : StudentId,
  'date' : Timestamp,
  'markedBy' : IDL.Text,
});
export const UpdateFeeInput = IDL.Record({
  'id' : FeeId,
  'status' : FeeStatus,
  'lateFeeAmount' : IDL.Nat,
  'dueDate' : Timestamp,
  'amount' : IDL.Nat,
  'receiptNumber' : IDL.Text,
});
export const UpdateMarkInput = IDL.Record({
  'id' : MarkId,
  'maxScore' : IDL.Nat,
  'assessmentName' : IDL.Text,
  'score' : IDL.Nat,
});
export const UpdateStudentInput = IDL.Record({
  'id' : StudentId,
  'parentContact' : IDL.Text,
  'grNo' : IDL.Text,
  'class' : IDL.Text,
  'name' : IDL.Text,
  'section' : IDL.Text,
  'photoUrl' : IDL.Text,
});
export const UpdateTeacherInput = IDL.Record({
  'id' : TeacherId,
  'classesAssigned' : IDL.Vec(IDL.Text),
  'subjects' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'teacherId' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMark' : IDL.Func([IDL.Text, AddMarkInput], [Mark], []),
  'addUser' : IDL.Func([IDL.Text, AddUserInput], [AddUserResult], []),
  'createFeeRecord' : IDL.Func([IDL.Text, CreateFeeInput], [FeeRecord], []),
  'createHomework' : IDL.Func([IDL.Text, CreateHomeworkInput], [Homework], []),
  'createNotice' : IDL.Func([IDL.Text, CreateNoticeInput], [Notice], []),
  'createStudent' : IDL.Func([IDL.Text, CreateStudentInput], [Student], []),
  'createTeacher' : IDL.Func([IDL.Text, CreateTeacherInput], [Teacher], []),
  'deleteNotice' : IDL.Func([IDL.Text, NoticeId], [IDL.Bool], []),
  'deleteStudent' : IDL.Func([IDL.Text, StudentId], [IDL.Bool], []),
  'deleteTeacher' : IDL.Func([IDL.Text, TeacherId], [IDL.Bool], []),
  'getAttendanceByClass' : IDL.Func(
      [IDL.Text, IDL.Text, Timestamp],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceByStudent' : IDL.Func(
      [IDL.Text, StudentId],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceRateSummary' : IDL.Func([], [AttendanceRateSummary], ['query']),
  'getAttendanceSummary' : IDL.Func(
      [IDL.Text, StudentId],
      [AttendanceSummary],
      ['query'],
    ),
  'getEnrollmentByClass' : IDL.Func(
      [],
      [IDL.Vec(EnrollmentByClass)],
      ['query'],
    ),
  'getFeesCollectionSummary' : IDL.Func([], [FeesCollectionSummary], ['query']),
  'getMarksByStudent' : IDL.Func(
      [IDL.Text, StudentId],
      [IDL.Vec(Mark)],
      ['query'],
    ),
  'getMarksBySubject' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Mark)],
      ['query'],
    ),
  'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
  'getSubmissions' : IDL.Func(
      [HomeworkId],
      [IDL.Vec(HomeworkSubmission)],
      ['query'],
    ),
  'getTeacher' : IDL.Func([TeacherId], [IDL.Opt(Teacher)], ['query']),
  'getTotalStudents' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalTeachers' : IDL.Func([], [IDL.Nat], ['query']),
  'listAllFees' : IDL.Func([], [IDL.Vec(FeeRecord)], ['query']),
  'listFeesByStudent' : IDL.Func([StudentId], [IDL.Vec(FeeRecord)], ['query']),
  'listHomeworkByClass' : IDL.Func([IDL.Text], [IDL.Vec(Homework)], ['query']),
  'listNotices' : IDL.Func(
      [IDL.Opt(Audience), IDL.Opt(IDL.Text)],
      [IDL.Vec(Notice)],
      ['query'],
    ),
  'listStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'listTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'logout' : IDL.Func([IDL.Text], [], []),
  'markAttendance' : IDL.Func(
      [IDL.Text, MarkAttendanceInput],
      [AttendanceRecord],
      [],
    ),
  'markFeePaid' : IDL.Func(
      [IDL.Text, FeeId, Timestamp],
      [IDL.Opt(FeeRecord)],
      [],
    ),
  'markSubmission' : IDL.Func(
      [IDL.Text, HomeworkId, StudentId],
      [HomeworkSubmission],
      [],
    ),
  'updateFeeRecord' : IDL.Func(
      [IDL.Text, UpdateFeeInput],
      [IDL.Opt(FeeRecord)],
      [],
    ),
  'updateMark' : IDL.Func([IDL.Text, UpdateMarkInput], [IDL.Opt(Mark)], []),
  'updateStudent' : IDL.Func(
      [IDL.Text, UpdateStudentInput],
      [IDL.Opt(Student)],
      [],
    ),
  'updateTeacher' : IDL.Func(
      [IDL.Text, UpdateTeacherInput],
      [IDL.Opt(Teacher)],
      [],
    ),
  'validateSession' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StudentId = IDL.Nat;
  const Timestamp = IDL.Int;
  const AddMarkInput = IDL.Record({
    'studentId' : StudentId,
    'maxScore' : IDL.Nat,
    'subject' : IDL.Text,
    'date' : Timestamp,
    'assessmentName' : IDL.Text,
    'score' : IDL.Nat,
  });
  const MarkId = IDL.Nat;
  const Mark = IDL.Record({
    'id' : MarkId,
    'studentId' : StudentId,
    'maxScore' : IDL.Nat,
    'subject' : IDL.Text,
    'date' : Timestamp,
    'assessmentName' : IDL.Text,
    'score' : IDL.Nat,
  });
  const AddUserInput = IDL.Record({
    'username' : IDL.Text,
    'password' : IDL.Text,
    'name' : IDL.Text,
    'roleId' : IDL.Text,
  });
  const Role = IDL.Variant({
    'Teacher' : IDL.Null,
    'Student' : IDL.Null,
    'Admin' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Text,
    'username' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : Role,
    'roleId' : IDL.Text,
  });
  const AddUserResult = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
  const CreateFeeInput = IDL.Record({
    'studentId' : StudentId,
    'lateFeeAmount' : IDL.Nat,
    'dueDate' : Timestamp,
    'amount' : IDL.Nat,
    'receiptNumber' : IDL.Text,
  });
  const FeeId = IDL.Nat;
  const FeeStatus = IDL.Variant({
    'Late' : IDL.Null,
    'Paid' : IDL.Null,
    'Unpaid' : IDL.Null,
  });
  const FeeRecord = IDL.Record({
    'id' : FeeId,
    'status' : FeeStatus,
    'studentId' : StudentId,
    'lateFeeAmount' : IDL.Nat,
    'dueDate' : Timestamp,
    'paidDate' : IDL.Opt(Timestamp),
    'amount' : IDL.Nat,
    'receiptNumber' : IDL.Text,
  });
  const CreateHomeworkInput = IDL.Record({
    'title' : IDL.Text,
    'createdBy' : IDL.Text,
    'dueDate' : Timestamp,
    'description' : IDL.Text,
    'classId' : IDL.Text,
  });
  const HomeworkId = IDL.Nat;
  const Homework = IDL.Record({
    'id' : HomeworkId,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : IDL.Text,
    'dueDate' : Timestamp,
    'description' : IDL.Text,
    'classId' : IDL.Text,
  });
  const Audience = IDL.Variant({
    'All' : IDL.Null,
    'Teacher' : IDL.Null,
    'Student' : IDL.Null,
    'Admin' : IDL.Null,
    'Class' : IDL.Null,
  });
  const CreateNoticeInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdBy' : IDL.Text,
    'audience' : Audience,
    'classId' : IDL.Opt(IDL.Text),
  });
  const NoticeId = IDL.Nat;
  const Notice = IDL.Record({
    'id' : NoticeId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : IDL.Text,
    'audience' : Audience,
    'classId' : IDL.Opt(IDL.Text),
  });
  const CreateStudentInput = IDL.Record({
    'parentContact' : IDL.Text,
    'grNo' : IDL.Text,
    'class' : IDL.Text,
    'name' : IDL.Text,
    'section' : IDL.Text,
    'photoUrl' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : StudentId,
    'parentContact' : IDL.Text,
    'grNo' : IDL.Text,
    'class' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'section' : IDL.Text,
    'photoUrl' : IDL.Text,
  });
  const CreateTeacherInput = IDL.Record({
    'classesAssigned' : IDL.Vec(IDL.Text),
    'subjects' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'teacherId' : IDL.Text,
  });
  const TeacherId = IDL.Nat;
  const Teacher = IDL.Record({
    'id' : TeacherId,
    'classesAssigned' : IDL.Vec(IDL.Text),
    'subjects' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'teacherId' : IDL.Text,
  });
  const AttendanceId = IDL.Nat;
  const AttendanceStatus = IDL.Variant({
    'Present' : IDL.Null,
    'Late' : IDL.Null,
    'Absent' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'id' : AttendanceId,
    'status' : AttendanceStatus,
    'studentId' : StudentId,
    'date' : Timestamp,
    'markedBy' : IDL.Text,
  });
  const AttendanceRateSummary = IDL.Record({
    'presentCount' : IDL.Nat,
    'attendanceRate' : IDL.Nat,
    'lateCount' : IDL.Nat,
    'totalRecords' : IDL.Nat,
    'absentCount' : IDL.Nat,
  });
  const AttendanceSummary = IDL.Record({
    'studentId' : StudentId,
    'presentDays' : IDL.Nat,
    'totalDays' : IDL.Nat,
    'lateDays' : IDL.Nat,
    'absentDays' : IDL.Nat,
  });
  const EnrollmentByClass = IDL.Record({
    'classId' : IDL.Text,
    'studentCount' : IDL.Nat,
  });
  const FeesCollectionSummary = IDL.Record({
    'lateAmount' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'pendingAmount' : IDL.Nat,
    'collectedAmount' : IDL.Nat,
  });
  const SubmissionStatus = IDL.Variant({
    'Submitted' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const HomeworkSubmission = IDL.Record({
    'status' : SubmissionStatus,
    'studentId' : StudentId,
    'homeworkId' : HomeworkId,
    'submittedAt' : Timestamp,
  });
  const LoginResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const MarkAttendanceInput = IDL.Record({
    'status' : AttendanceStatus,
    'studentId' : StudentId,
    'date' : Timestamp,
    'markedBy' : IDL.Text,
  });
  const UpdateFeeInput = IDL.Record({
    'id' : FeeId,
    'status' : FeeStatus,
    'lateFeeAmount' : IDL.Nat,
    'dueDate' : Timestamp,
    'amount' : IDL.Nat,
    'receiptNumber' : IDL.Text,
  });
  const UpdateMarkInput = IDL.Record({
    'id' : MarkId,
    'maxScore' : IDL.Nat,
    'assessmentName' : IDL.Text,
    'score' : IDL.Nat,
  });
  const UpdateStudentInput = IDL.Record({
    'id' : StudentId,
    'parentContact' : IDL.Text,
    'grNo' : IDL.Text,
    'class' : IDL.Text,
    'name' : IDL.Text,
    'section' : IDL.Text,
    'photoUrl' : IDL.Text,
  });
  const UpdateTeacherInput = IDL.Record({
    'id' : TeacherId,
    'classesAssigned' : IDL.Vec(IDL.Text),
    'subjects' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'teacherId' : IDL.Text,
  });
  
  return IDL.Service({
    'addMark' : IDL.Func([IDL.Text, AddMarkInput], [Mark], []),
    'addUser' : IDL.Func([IDL.Text, AddUserInput], [AddUserResult], []),
    'createFeeRecord' : IDL.Func([IDL.Text, CreateFeeInput], [FeeRecord], []),
    'createHomework' : IDL.Func(
        [IDL.Text, CreateHomeworkInput],
        [Homework],
        [],
      ),
    'createNotice' : IDL.Func([IDL.Text, CreateNoticeInput], [Notice], []),
    'createStudent' : IDL.Func([IDL.Text, CreateStudentInput], [Student], []),
    'createTeacher' : IDL.Func([IDL.Text, CreateTeacherInput], [Teacher], []),
    'deleteNotice' : IDL.Func([IDL.Text, NoticeId], [IDL.Bool], []),
    'deleteStudent' : IDL.Func([IDL.Text, StudentId], [IDL.Bool], []),
    'deleteTeacher' : IDL.Func([IDL.Text, TeacherId], [IDL.Bool], []),
    'getAttendanceByClass' : IDL.Func(
        [IDL.Text, IDL.Text, Timestamp],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceByStudent' : IDL.Func(
        [IDL.Text, StudentId],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceRateSummary' : IDL.Func(
        [],
        [AttendanceRateSummary],
        ['query'],
      ),
    'getAttendanceSummary' : IDL.Func(
        [IDL.Text, StudentId],
        [AttendanceSummary],
        ['query'],
      ),
    'getEnrollmentByClass' : IDL.Func(
        [],
        [IDL.Vec(EnrollmentByClass)],
        ['query'],
      ),
    'getFeesCollectionSummary' : IDL.Func(
        [],
        [FeesCollectionSummary],
        ['query'],
      ),
    'getMarksByStudent' : IDL.Func(
        [IDL.Text, StudentId],
        [IDL.Vec(Mark)],
        ['query'],
      ),
    'getMarksBySubject' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Mark)],
        ['query'],
      ),
    'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
    'getSubmissions' : IDL.Func(
        [HomeworkId],
        [IDL.Vec(HomeworkSubmission)],
        ['query'],
      ),
    'getTeacher' : IDL.Func([TeacherId], [IDL.Opt(Teacher)], ['query']),
    'getTotalStudents' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalTeachers' : IDL.Func([], [IDL.Nat], ['query']),
    'listAllFees' : IDL.Func([], [IDL.Vec(FeeRecord)], ['query']),
    'listFeesByStudent' : IDL.Func(
        [StudentId],
        [IDL.Vec(FeeRecord)],
        ['query'],
      ),
    'listHomeworkByClass' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Homework)],
        ['query'],
      ),
    'listNotices' : IDL.Func(
        [IDL.Opt(Audience), IDL.Opt(IDL.Text)],
        [IDL.Vec(Notice)],
        ['query'],
      ),
    'listStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'listTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'logout' : IDL.Func([IDL.Text], [], []),
    'markAttendance' : IDL.Func(
        [IDL.Text, MarkAttendanceInput],
        [AttendanceRecord],
        [],
      ),
    'markFeePaid' : IDL.Func(
        [IDL.Text, FeeId, Timestamp],
        [IDL.Opt(FeeRecord)],
        [],
      ),
    'markSubmission' : IDL.Func(
        [IDL.Text, HomeworkId, StudentId],
        [HomeworkSubmission],
        [],
      ),
    'updateFeeRecord' : IDL.Func(
        [IDL.Text, UpdateFeeInput],
        [IDL.Opt(FeeRecord)],
        [],
      ),
    'updateMark' : IDL.Func([IDL.Text, UpdateMarkInput], [IDL.Opt(Mark)], []),
    'updateStudent' : IDL.Func(
        [IDL.Text, UpdateStudentInput],
        [IDL.Opt(Student)],
        [],
      ),
    'updateTeacher' : IDL.Func(
        [IDL.Text, UpdateTeacherInput],
        [IDL.Opt(Teacher)],
        [],
      ),
    'validateSession' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };