/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MarkAttendanceInput {
    status: AttendanceStatus;
    studentId: StudentId;
    date: Timestamp;
    markedBy: string;
}
export type Timestamp = bigint;
export interface EnrollmentByClass {
    classId: string;
    studentCount: bigint;
}
export interface CreateFeeInput {
    studentId: StudentId;
    lateFeeAmount: bigint;
    dueDate: Timestamp;
    amount: bigint;
    receiptNumber: string;
}
export type AttendanceId = bigint;
export interface Teacher {
    id: TeacherId;
    classesAssigned: Array<string>;
    subjects: Array<string>;
    name: string;
    createdAt: Timestamp;
    teacherId: string;
}
export interface UpdateStudentInput {
    id: StudentId;
    parentContact: string;
    grNo: string;
    class: string;
    name: string;
    section: string;
    photoUrl: string;
}
export interface CreateNoticeInput {
    title: string;
    content: string;
    createdBy: string;
    audience: Audience;
    classId?: string;
}
export type MarkId = bigint;
export interface FeeRecord {
    id: FeeId;
    status: FeeStatus;
    studentId: StudentId;
    lateFeeAmount: bigint;
    dueDate: Timestamp;
    paidDate?: Timestamp;
    amount: bigint;
    receiptNumber: string;
}
export type FeeId = bigint;
export interface UpdateMarkInput {
    id: MarkId;
    maxScore: bigint;
    assessmentName: string;
    score: bigint;
}
export interface FeesCollectionSummary {
    lateAmount: bigint;
    totalAmount: bigint;
    pendingAmount: bigint;
    collectedAmount: bigint;
}
export interface Notice {
    id: NoticeId;
    title: string;
    content: string;
    createdAt: Timestamp;
    createdBy: string;
    audience: Audience;
    classId?: string;
}
export interface Mark {
    id: MarkId;
    studentId: StudentId;
    maxScore: bigint;
    subject: string;
    date: Timestamp;
    assessmentName: string;
    score: bigint;
}
export interface Homework {
    id: HomeworkId;
    title: string;
    createdAt: Timestamp;
    createdBy: string;
    dueDate: Timestamp;
    description: string;
    classId: string;
}
export type NoticeId = bigint;
export interface AttendanceRecord {
    id: AttendanceId;
    status: AttendanceStatus;
    studentId: StudentId;
    date: Timestamp;
    markedBy: string;
}
export interface Student {
    id: StudentId;
    parentContact: string;
    grNo: string;
    class: string;
    name: string;
    createdAt: Timestamp;
    section: string;
    photoUrl: string;
}
export interface HomeworkSubmission {
    status: SubmissionStatus;
    studentId: StudentId;
    homeworkId: HomeworkId;
    submittedAt: Timestamp;
}
export interface CreateStudentInput {
    parentContact: string;
    grNo: string;
    class: string;
    name: string;
    section: string;
    photoUrl: string;
}
export interface CreateTeacherInput {
    classesAssigned: Array<string>;
    subjects: Array<string>;
    name: string;
    teacherId: string;
}
export interface UpdateFeeInput {
    id: FeeId;
    status: FeeStatus;
    lateFeeAmount: bigint;
    dueDate: Timestamp;
    amount: bigint;
    receiptNumber: string;
}
export interface AttendanceSummary {
    studentId: StudentId;
    presentDays: bigint;
    totalDays: bigint;
    lateDays: bigint;
    absentDays: bigint;
}
export interface AttendanceRateSummary {
    presentCount: bigint;
    attendanceRate: bigint;
    lateCount: bigint;
    totalRecords: bigint;
    absentCount: bigint;
}
export type StudentId = bigint;
export type TeacherId = bigint;
export type HomeworkId = bigint;
export interface CreateHomeworkInput {
    title: string;
    createdBy: string;
    dueDate: Timestamp;
    description: string;
    classId: string;
}
export type AddUserResult = {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
};
export interface AddUserInput {
    username: string;
    password: string;
    name: string;
    roleId: string;
}
export type LoginResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface UpdateTeacherInput {
    id: TeacherId;
    classesAssigned: Array<string>;
    subjects: Array<string>;
    name: string;
    teacherId: string;
}
export interface UserProfile {
    id: string;
    username: string;
    name: string;
    createdAt: Timestamp;
    role: Role;
    roleId: string;
}
export interface AddMarkInput {
    studentId: StudentId;
    maxScore: bigint;
    subject: string;
    date: Timestamp;
    assessmentName: string;
    score: bigint;
}
export enum AttendanceStatus {
    Present = "Present",
    Late = "Late",
    Absent = "Absent"
}
export enum Audience {
    All = "All",
    Teacher = "Teacher",
    Student = "Student",
    Admin = "Admin",
    Class = "Class"
}
export enum FeeStatus {
    Late = "Late",
    Paid = "Paid",
    Unpaid = "Unpaid"
}
export enum Role {
    Teacher = "Teacher",
    Student = "Student",
    Admin = "Admin"
}
export enum SubmissionStatus {
    Submitted = "Submitted",
    Pending = "Pending"
}
export interface backendInterface {
    addMark(token: string, input: AddMarkInput): Promise<Mark>;
    addUser(token: string, input: AddUserInput): Promise<AddUserResult>;
    createFeeRecord(token: string, input: CreateFeeInput): Promise<FeeRecord>;
    createHomework(token: string, input: CreateHomeworkInput): Promise<Homework>;
    createNotice(token: string, input: CreateNoticeInput): Promise<Notice>;
    createStudent(token: string, input: CreateStudentInput): Promise<Student>;
    createTeacher(token: string, input: CreateTeacherInput): Promise<Teacher>;
    deleteNotice(token: string, id: NoticeId): Promise<boolean>;
    deleteStudent(token: string, id: StudentId): Promise<boolean>;
    deleteTeacher(token: string, id: TeacherId): Promise<boolean>;
    getAttendanceByClass(token: string, classId: string, date: Timestamp): Promise<Array<AttendanceRecord>>;
    getAttendanceByStudent(token: string, studentId: StudentId): Promise<Array<AttendanceRecord>>;
    getAttendanceRateSummary(): Promise<AttendanceRateSummary>;
    getAttendanceSummary(token: string, studentId: StudentId): Promise<AttendanceSummary>;
    getEnrollmentByClass(): Promise<Array<EnrollmentByClass>>;
    getFeesCollectionSummary(): Promise<FeesCollectionSummary>;
    getMarksByStudent(token: string, studentId: StudentId): Promise<Array<Mark>>;
    getMarksBySubject(token: string, subject: string): Promise<Array<Mark>>;
    getStudent(id: StudentId): Promise<Student | null>;
    getSubmissions(homeworkId: HomeworkId): Promise<Array<HomeworkSubmission>>;
    getTeacher(id: TeacherId): Promise<Teacher | null>;
    getTotalStudents(): Promise<bigint>;
    getTotalTeachers(): Promise<bigint>;
    listAllFees(): Promise<Array<FeeRecord>>;
    listFeesByStudent(studentId: StudentId): Promise<Array<FeeRecord>>;
    listHomeworkByClass(classId: string): Promise<Array<Homework>>;
    listNotices(audience: Audience | null, classId: string | null): Promise<Array<Notice>>;
    listStudents(): Promise<Array<Student>>;
    listTeachers(): Promise<Array<Teacher>>;
    login(username: string, password: string): Promise<LoginResult>;
    logout(token: string): Promise<void>;
    markAttendance(token: string, input: MarkAttendanceInput): Promise<AttendanceRecord>;
    markFeePaid(token: string, id: FeeId, paidDate: Timestamp): Promise<FeeRecord | null>;
    markSubmission(token: string, homeworkId: HomeworkId, studentId: StudentId): Promise<HomeworkSubmission>;
    updateFeeRecord(token: string, input: UpdateFeeInput): Promise<FeeRecord | null>;
    updateMark(token: string, input: UpdateMarkInput): Promise<Mark | null>;
    updateStudent(token: string, input: UpdateStudentInput): Promise<Student | null>;
    updateTeacher(token: string, input: UpdateTeacherInput): Promise<Teacher | null>;
    validateSession(token: string): Promise<UserProfile | null>;
}
import type { AddUserResult as _AddUserResult, AttendanceId as _AttendanceId, AttendanceRecord as _AttendanceRecord, AttendanceStatus as _AttendanceStatus, Audience as _Audience, CreateNoticeInput as _CreateNoticeInput, FeeId as _FeeId, FeeRecord as _FeeRecord, FeeStatus as _FeeStatus, HomeworkId as _HomeworkId, HomeworkSubmission as _HomeworkSubmission, LoginResult as _LoginResult, Mark as _Mark, MarkAttendanceInput as _MarkAttendanceInput, Notice as _Notice, NoticeId as _NoticeId, Role as _Role, Student as _Student, StudentId as _StudentId, SubmissionStatus as _SubmissionStatus, Teacher as _Teacher, Timestamp as _Timestamp, UpdateFeeInput as _UpdateFeeInput, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addMark(arg0: string, arg1: AddMarkInput): Promise<Mark> {
        if (this.processError) {
            try {
                const result = await this.actor.addMark(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMark(arg0, arg1);
            return result;
        }
    }
    async addUser(arg0: string, arg1: AddUserInput): Promise<AddUserResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addUser(arg0, arg1);
                return from_candid_AddUserResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUser(arg0, arg1);
            return from_candid_AddUserResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createFeeRecord(arg0: string, arg1: CreateFeeInput): Promise<FeeRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.createFeeRecord(arg0, arg1);
                return from_candid_FeeRecord_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFeeRecord(arg0, arg1);
            return from_candid_FeeRecord_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async createHomework(arg0: string, arg1: CreateHomeworkInput): Promise<Homework> {
        if (this.processError) {
            try {
                const result = await this.actor.createHomework(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHomework(arg0, arg1);
            return result;
        }
    }
    async createNotice(arg0: string, arg1: CreateNoticeInput): Promise<Notice> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotice(arg0, to_candid_CreateNoticeInput_n12(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Notice_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotice(arg0, to_candid_CreateNoticeInput_n12(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Notice_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async createStudent(arg0: string, arg1: CreateStudentInput): Promise<Student> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudent(arg0, arg1);
            return result;
        }
    }
    async createTeacher(arg0: string, arg1: CreateTeacherInput): Promise<Teacher> {
        if (this.processError) {
            try {
                const result = await this.actor.createTeacher(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTeacher(arg0, arg1);
            return result;
        }
    }
    async deleteNotice(arg0: string, arg1: NoticeId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotice(arg0, arg1);
            return result;
        }
    }
    async deleteStudent(arg0: string, arg1: StudentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0, arg1);
            return result;
        }
    }
    async deleteTeacher(arg0: string, arg1: TeacherId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeacher(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeacher(arg0, arg1);
            return result;
        }
    }
    async getAttendanceByClass(arg0: string, arg1: string, arg2: Timestamp): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByClass(arg0, arg1, arg2);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByClass(arg0, arg1, arg2);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceByStudent(arg0: string, arg1: StudentId): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByStudent(arg0, arg1);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByStudent(arg0, arg1);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceRateSummary(): Promise<AttendanceRateSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceRateSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceRateSummary();
            return result;
        }
    }
    async getAttendanceSummary(arg0: string, arg1: StudentId): Promise<AttendanceSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceSummary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceSummary(arg0, arg1);
            return result;
        }
    }
    async getEnrollmentByClass(): Promise<Array<EnrollmentByClass>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnrollmentByClass();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnrollmentByClass();
            return result;
        }
    }
    async getFeesCollectionSummary(): Promise<FeesCollectionSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeesCollectionSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeesCollectionSummary();
            return result;
        }
    }
    async getMarksByStudent(arg0: string, arg1: StudentId): Promise<Array<Mark>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarksByStudent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarksByStudent(arg0, arg1);
            return result;
        }
    }
    async getMarksBySubject(arg0: string, arg1: string): Promise<Array<Mark>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarksBySubject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarksBySubject(arg0, arg1);
            return result;
        }
    }
    async getStudent(arg0: StudentId): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmissions(arg0: HomeworkId): Promise<Array<HomeworkSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissions(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissions(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeacher(arg0: TeacherId): Promise<Teacher | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacher(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacher(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalStudents(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalStudents();
            return result;
        }
    }
    async getTotalTeachers(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalTeachers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalTeachers();
            return result;
        }
    }
    async listAllFees(): Promise<Array<FeeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllFees();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllFees();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFeesByStudent(arg0: StudentId): Promise<Array<FeeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFeesByStudent(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFeesByStudent(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listHomeworkByClass(arg0: string): Promise<Array<Homework>> {
        if (this.processError) {
            try {
                const result = await this.actor.listHomeworkByClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listHomeworkByClass(arg0);
            return result;
        }
    }
    async listNotices(arg0: Audience | null, arg1: string | null): Promise<Array<Notice>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNotices(to_candid_opt_n34(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n35(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNotices(to_candid_opt_n34(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n35(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async listStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudents();
            return result;
        }
    }
    async listTeachers(): Promise<Array<Teacher>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTeachers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTeachers();
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_LoginResult_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_LoginResult_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout(arg0);
            return result;
        }
    }
    async markAttendance(arg0: string, arg1: MarkAttendanceInput): Promise<AttendanceRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.markAttendance(arg0, to_candid_MarkAttendanceInput_n39(this._uploadFile, this._downloadFile, arg1));
                return from_candid_AttendanceRecord_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAttendance(arg0, to_candid_MarkAttendanceInput_n39(this._uploadFile, this._downloadFile, arg1));
            return from_candid_AttendanceRecord_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async markFeePaid(arg0: string, arg1: FeeId, arg2: Timestamp): Promise<FeeRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.markFeePaid(arg0, arg1, arg2);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markFeePaid(arg0, arg1, arg2);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async markSubmission(arg0: string, arg1: HomeworkId, arg2: StudentId): Promise<HomeworkSubmission> {
        if (this.processError) {
            try {
                const result = await this.actor.markSubmission(arg0, arg1, arg2);
                return from_candid_HomeworkSubmission_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markSubmission(arg0, arg1, arg2);
            return from_candid_HomeworkSubmission_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateFeeRecord(arg0: string, arg1: UpdateFeeInput): Promise<FeeRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFeeRecord(arg0, to_candid_UpdateFeeInput_n44(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFeeRecord(arg0, to_candid_UpdateFeeInput_n44(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMark(arg0: string, arg1: UpdateMarkInput): Promise<Mark | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMark(arg0, arg1);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMark(arg0, arg1);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateStudent(arg0: string, arg1: UpdateStudentInput): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, arg1);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, arg1);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTeacher(arg0: string, arg1: UpdateTeacherInput): Promise<Teacher | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeacher(arg0, arg1);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeacher(arg0, arg1);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateSession(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.validateSession(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateSession(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AddUserResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AddUserResult): AddUserResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceRecord_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceStatus): AttendanceStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Audience_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Audience): Audience {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_FeeRecord_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeRecord): FeeRecord {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_FeeStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeStatus): FeeStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_HomeworkSubmission_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HomeworkSubmission): HomeworkSubmission {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_LoginResult_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginResult): LoginResult {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Notice_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notice): Notice {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_SubmissionStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmissionStatus): SubmissionStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Teacher]): Teacher | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FeeRecord]): FeeRecord | null {
    return value.length === 0 ? null : from_candid_FeeRecord_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Mark]): Mark | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NoticeId;
    title: string;
    content: string;
    createdAt: _Timestamp;
    createdBy: string;
    audience: _Audience;
    classId: [] | [string];
}): {
    id: NoticeId;
    title: string;
    content: string;
    createdAt: Timestamp;
    createdBy: string;
    audience: Audience;
    classId?: string;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        audience: from_candid_Audience_n18(_uploadFile, _downloadFile, value.audience),
        classId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.classId))
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AttendanceId;
    status: _AttendanceStatus;
    studentId: _StudentId;
    date: _Timestamp;
    markedBy: string;
}): {
    id: AttendanceId;
    status: AttendanceStatus;
    studentId: StudentId;
    date: Timestamp;
    markedBy: string;
} {
    return {
        id: value.id,
        status: from_candid_AttendanceStatus_n24(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        date: value.date,
        markedBy: value.markedBy
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _SubmissionStatus;
    studentId: _StudentId;
    homeworkId: _HomeworkId;
    submittedAt: _Timestamp;
}): {
    status: SubmissionStatus;
    studentId: StudentId;
    homeworkId: HomeworkId;
    submittedAt: Timestamp;
} {
    return {
        status: from_candid_SubmissionStatus_n30(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        homeworkId: value.homeworkId,
        submittedAt: value.submittedAt
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    username: string;
    name: string;
    createdAt: _Timestamp;
    role: _Role;
    roleId: string;
}): {
    id: string;
    username: string;
    name: string;
    createdAt: Timestamp;
    role: Role;
    roleId: string;
} {
    return {
        id: value.id,
        username: value.username,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_Role_n5(_uploadFile, _downloadFile, value.role),
        roleId: value.roleId
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FeeId;
    status: _FeeStatus;
    studentId: _StudentId;
    lateFeeAmount: bigint;
    dueDate: _Timestamp;
    paidDate: [] | [_Timestamp];
    amount: bigint;
    receiptNumber: string;
}): {
    id: FeeId;
    status: FeeStatus;
    studentId: StudentId;
    lateFeeAmount: bigint;
    dueDate: Timestamp;
    paidDate?: Timestamp;
    amount: bigint;
    receiptNumber: string;
} {
    return {
        id: value.id,
        status: from_candid_FeeStatus_n9(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        lateFeeAmount: value.lateFeeAmount,
        dueDate: value.dueDate,
        paidDate: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.paidDate)),
        amount: value.amount,
        receiptNumber: value.receiptNumber
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Late: null;
} | {
    Paid: null;
} | {
    Unpaid: null;
}): FeeStatus {
    return "Late" in value ? FeeStatus.Late : "Paid" in value ? FeeStatus.Paid : "Unpaid" in value ? FeeStatus.Unpaid : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    All: null;
} | {
    Teacher: null;
} | {
    Student: null;
} | {
    Admin: null;
} | {
    Class: null;
}): Audience {
    return "All" in value ? Audience.All : "Teacher" in value ? Audience.Teacher : "Student" in value ? Audience.Student : "Admin" in value ? Audience.Admin : "Class" in value ? Audience.Class : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfile_n3(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Present: null;
} | {
    Late: null;
} | {
    Absent: null;
}): AttendanceStatus {
    return "Present" in value ? AttendanceStatus.Present : "Late" in value ? AttendanceStatus.Late : "Absent" in value ? AttendanceStatus.Absent : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Submitted: null;
} | {
    Pending: null;
}): SubmissionStatus {
    return "Submitted" in value ? SubmissionStatus.Submitted : "Pending" in value ? SubmissionStatus.Pending : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Teacher: null;
} | {
    Student: null;
} | {
    Admin: null;
}): Role {
    return "Teacher" in value ? Role.Teacher : "Student" in value ? Role.Student : "Admin" in value ? Role.Admin : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Array<AttendanceRecord> {
    return value.map((x)=>from_candid_AttendanceRecord_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HomeworkSubmission>): Array<HomeworkSubmission> {
    return value.map((x)=>from_candid_HomeworkSubmission_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeeRecord>): Array<FeeRecord> {
    return value.map((x)=>from_candid_FeeRecord_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notice>): Array<Notice> {
    return value.map((x)=>from_candid_Notice_n16(_uploadFile, _downloadFile, x));
}
function to_candid_AttendanceStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): _AttendanceStatus {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_Audience_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Audience): _Audience {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_CreateNoticeInput_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateNoticeInput): _CreateNoticeInput {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_FeeStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeeStatus): _FeeStatus {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_MarkAttendanceInput_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarkAttendanceInput): _MarkAttendanceInput {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateFeeInput_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateFeeInput): _UpdateFeeInput {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Audience | null): [] | [_Audience] {
    return value === null ? candid_none() : candid_some(to_candid_Audience_n14(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    createdBy: string;
    audience: Audience;
    classId?: string;
}): {
    title: string;
    content: string;
    createdBy: string;
    audience: _Audience;
    classId: [] | [string];
} {
    return {
        title: value.title,
        content: value.content,
        createdBy: value.createdBy,
        audience: to_candid_Audience_n14(_uploadFile, _downloadFile, value.audience),
        classId: value.classId ? candid_some(value.classId) : candid_none()
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: AttendanceStatus;
    studentId: StudentId;
    date: Timestamp;
    markedBy: string;
}): {
    status: _AttendanceStatus;
    studentId: _StudentId;
    date: _Timestamp;
    markedBy: string;
} {
    return {
        status: to_candid_AttendanceStatus_n41(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        date: value.date,
        markedBy: value.markedBy
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: FeeId;
    status: FeeStatus;
    lateFeeAmount: bigint;
    dueDate: Timestamp;
    amount: bigint;
    receiptNumber: string;
}): {
    id: _FeeId;
    status: _FeeStatus;
    lateFeeAmount: bigint;
    dueDate: _Timestamp;
    amount: bigint;
    receiptNumber: string;
} {
    return {
        id: value.id,
        status: to_candid_FeeStatus_n46(_uploadFile, _downloadFile, value.status),
        lateFeeAmount: value.lateFeeAmount,
        dueDate: value.dueDate,
        amount: value.amount,
        receiptNumber: value.receiptNumber
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Audience): {
    All: null;
} | {
    Teacher: null;
} | {
    Student: null;
} | {
    Admin: null;
} | {
    Class: null;
} {
    return value == Audience.All ? {
        All: null
    } : value == Audience.Teacher ? {
        Teacher: null
    } : value == Audience.Student ? {
        Student: null
    } : value == Audience.Admin ? {
        Admin: null
    } : value == Audience.Class ? {
        Class: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): {
    Present: null;
} | {
    Late: null;
} | {
    Absent: null;
} {
    return value == AttendanceStatus.Present ? {
        Present: null
    } : value == AttendanceStatus.Late ? {
        Late: null
    } : value == AttendanceStatus.Absent ? {
        Absent: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeeStatus): {
    Late: null;
} | {
    Paid: null;
} | {
    Unpaid: null;
} {
    return value == FeeStatus.Late ? {
        Late: null
    } : value == FeeStatus.Paid ? {
        Paid: null
    } : value == FeeStatus.Unpaid ? {
        Unpaid: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
